### ISSUE TITLE
No module named 'tree_filter_cuda' 

### ISSUE THREAD

**Issue by mirzaqasem** [llmir/FedICRA#1]
hi
thank you for sharing your code
but in google colab  can not run it because

ModuleNotFoundError: No module named 'tree_filter_cuda'

in three file mst .py, bfs .py and refine .py

please help

**Comment by llmir** [comment]
Please navigate to the root directory and execute the command "pip install tree_filter-0.1-cp39-cp39-linux_x86_64.whl". If it doesn't work, please refer to and follow the environment configuration steps provided at https://github.com/megvii-research/TreeEnergyLoss. I hope this helps, and if possible, please consider giving a star to the repository. ☺

**Comment by mirzaqasem** [comment]
!python 'flower_runner.py' --port 8097 --procedure 'flower_pCE_2D_GateCRFMsacleTreeEnergyLoss_Ours' --exp faz/WeaklySeg_pCE --base_lr 0.01 --img_class faz --model unet_lc_multihead --gpus 0 1 2 3 4 5 --strategy FedICRA --alpha 1 --rep_iters 3

Traceback (most recent call last):
  File "/content/FedICRA/code/flower_pCE_2D_GateCRFMsacleTreeEnergyLoss_Ours.py", line 38, in <module>
    from flower_common import (BaseClient, MyModel, fit_metrics_aggregation_fn, TreeEnergyLoss,MScaleRecurveTreeEnergyLoss, evaluate, get_evaluate_fn,
  File "/content/FedICRA/code/flower_common.py", line 31, in <module>
    from utils.TreeEnergyLoss.kernels.lib_tree_filter.modules.tree_filter import MinimumSpanningTree
  File "/content/FedICRA/code/utils/TreeEnergyLoss/kernels/lib_tree_filter/modules/tree_filter.py", line 5, in <module>
    from ..functions.mst import mst
  File "/content/FedICRA/code/utils/TreeEnergyLoss/kernels/lib_tree_filter/functions/mst.py", line 7, in <module>
    import tree_filter_cuda as _C
ModuleNotFoundError: No module named 'tree_filter_cuda'
Running "python flower_pCE_2D_GateCRFMsacleTreeEnergyLoss_Ours.py --root_path ../data/FAZ_h5 --num_classes 2 --in_chns 1 --img_class faz --exp faz/WeaklySeg_pCE --model unet_lc_multihead --max_iterations 30000 --iters 10 --img_size 256 --eval_iters 20 --batch_size 12 --base_lr 0.01 --amp 0 --server_address [::]:8097 --strategy FedICRA --min_num_clients 5 --tree_loss_weight 0.1 --alpha 1.0 --rep_iters 3 --role client --cid 0 --client client1 --sup_type scribble_noisy --gpu 1"

Traceback (most recent call last):
  File "/content/FedICRA/code/flower_pCE_2D_GateCRFMsacleTreeEnergyLoss_Ours.py", line 38, in <module>
    from flower_common import (BaseClient, MyModel, fit_metrics_aggregation_fn, TreeEnergyLoss,MScaleRecurveTreeEnergyLoss, evaluate, get_evaluate_fn,
  File "/content/FedICRA/code/flower_common.py", line 31, in <module>
    from utils.TreeEnergyLoss.kernels.lib_tree_filter.modules.tree_filter import MinimumSpanningTree
  File "/content/FedICRA/code/utils/TreeEnergyLoss/kernels/lib_tree_filter/modules/tree_filter.py", line 5, in <module>
    from ..functions.mst import mst
  File "/content/FedICRA/code/utils/TreeEnergyLoss/kernels/lib_tree_filter/functions/mst.py", line 7, in <module>
    import tree_filter_cuda as _C
ModuleNotFoundError: No module named 'tree_filter_cuda'
Running "python flower_pCE_2D_GateCRFMsacleTreeEnergyLoss_Ours.py --root_path ../data/FAZ_h5 --num_classes 2 --in_chns 1 --img_class faz --exp faz/WeaklySeg_pCE --model unet_lc_multihead --max_iterations 30000 --iters 10 --img_size 256 --eval_iters 20 --batch_size 12 --base_lr 0.01 --amp 0 --server_address [::]:8097 --strategy FedICRA --min_num_clients 5 --tree_loss_weight 0.1 --alpha 1.0 --rep_iters 3 --role client --cid 1 --client client2 --sup_type keypoint --gpu 2"

Process ForkPoolWorker-5:
Process ForkPoolWorker-6:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/local/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/local/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
Process ForkPoolWorker-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 365, in get
    res = self._reader.recv_bytes()
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Process ForkPoolWorker-2:
Process ForkPoolWorker-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/content/FedICRA/code/flower_runner.py", line 116, in <module>
    time.sleep(7)
KeyboardInterrupt
Traceback (most recent call last):
  File "/content/FedICRA/code/flower_pCE_2D_GateCRFMsacleTreeEnergyLoss_Ours.py", line 11, in <module>
    import torch
  File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 1465, in <module>
    from . import _meta_registrations
  File "/usr/local/lib/python3.10/site-packages/torch/_meta_registrations.py", line 7, in <module>
    from torch._decomp import _add_op_to_registry, global_decomposition_table, meta_table
  File "/usr/local/lib/python3.10/site-packages/torch/_decomp/__init__.py", line 169, in <module>
    import torch._decomp.decompositions
  File "/usr/local/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 10, in <module>
    import torch._prims as prims
  File "/usr/local/lib/python3.10/site-packages/torch/_prims/__init__.py", line 2882, in <module>
    register_nvprims()
  File "/usr/local/lib/python3.10/site-packages/torch/_prims/nvfuser_prims.py", line 824, in register_nvprims
    nvprim_autograd_impl.impl(name, backwards_not_supported(prim))
  File "/usr/local/lib/python3.10/site-packages/torch/library.py", line 126, in impl
Exception ignored in atexit callback: <function _exit_function at 0x7fb607f33130>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
    self.m.impl(name, dispatch_key if dispatch_key != "" else "CompositeImplicitAutograd", fn)
KeyboardInterrupt
    _run_finalizers(0)
  File "/usr/local/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/local/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 695, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 675, in _help_stuff_finish
    inqueue._rlock.acquire()
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/local/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/local/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
^C
